### PR TITLE
Rename inputDir to inputPath, customize outputDirectory

### PR DESCRIPTION
**Pull request by benjamin-bader**

### CODE REVIEW

**Comment by benjamin-bader** [comment]
@jparise this might make you happier.

**Comment by jparise** [comment]
This looks good to me. Could you update the `README.md` to demonstrate the new names, too?

**Comment by benjamin-bader** [comment]
Wow, I learned a ton about Gradle and like 80% of the plugin class was unnecessary.

**Comment by jparise** [comment]
Looking forward to giving this a spin. Are you planning a point release?

**Comment by benjamin-bader** [comment]
Yep.  I'm doing a bit more research first to see if I can figure out how to make IDE integration work properly, but time-boxing it.  Also trying to figure out a way to avoid a Kotlin-specific failure mode, but without much hope.  Will make a release after.

**Comment by benjamin-bader** [comment]
@jparise it's a little later than I'd thought, but 2.1.1 is live in Maven Central now.

**Comment by jparise** [comment]
@benjamin-bader I'm still running into weird ANTLR issues with the published 2.1.1 version.

Out of the box, the error is:

```
ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.5.3ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.5.3
```

And if I apply the frequent `resolutionStrategy.force` suggestion, e.g.:

```
            resolutionStrategy.force "org.antlr:antlr4-runtime:4.8-1"
            resolutionStrategy.force "org.antlr:antlr4-tool:4.8-1"
```

... then I run into:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.thrifty.schema.antlr.AntlrThriftLexer
        at com.microsoft.thrifty.schema.parser.ThriftParser.parse(ThriftParser.kt:53)
        at com.microsoft.thrifty.schema.Loader.loadSingleFile(Loader.kt:240)
        at com.microsoft.thrifty.schema.Loader.loadFileRecursively(Loader.kt:195)
        at com.microsoft.thrifty.schema.Loader.loadFileRecursively$default(Loader.kt:183)
        at com.microsoft.thrifty.schema.Loader.loadFromDisk(Loader.kt:149)
        at com.microsoft.thrifty.schema.Loader.load(Loader.kt:120)
        at com.microsoft.thrifty.gradle.ThriftyTask.run(ThriftyTask.kt:72)
```

I can't force it to a lower version (such as 4.5.3) because Thrifty uses ANTLR interfaces introduced in 4.8 (a "byte stream" class, I think).

**Comment by benjamin-bader** [comment]
This is truly bizarre.  I can't find any references to antlr version 4.5.3 in the project.

Would you please run `./gradlew dependencyInsight --dependency antlr` and let me know what you see there? (the task name will depend on where you're using the plugin, e.g. if you're adding it to `app/build.gradle` the task should be `:app:dependencyInsight`)

**Comment by jparise** [comment]
It took my a lot of fiddling and reading, but I ultimately learned that `dependencyInsight` doesn't work for build-time dependencies. Instead, you need to use `buildEnvironment`:

<details>
```
classpath
\--- com.microsoft.thrifty:com.microsoft.thrifty.gradle.plugin:2.1.1
     \--- com.microsoft.thrifty:thrifty-gradle-plugin:2.1.1
          +--- com.microsoft.thrifty:thrifty-java-codegen:2.1.1
          |    +--- com.microsoft.thrifty:thrifty-runtime:2.1.1
          |    |    \--- com.squareup.okio:okio:2.6.0
          |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.70 -> 1.3.72
          |    |         |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
          |    |         |    \--- org.jetbrains:annotations:13.0
          |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.70 -> 1.3.72
          |    +--- com.microsoft.thrifty:thrifty-schema:2.1.1
          |    |    +--- org.antlr:antlr4:4.8-1
          |    |    |    +--- org.antlr:antlr4-runtime:4.8-1
          |    |    |    +--- org.antlr:antlr-runtime:3.5.2
          |    |    |    +--- org.antlr:ST4:4.3
          |    |    |    |    \--- org.antlr:antlr-runtime:3.5.2
          |    |    |    +--- org.abego.treelayout:org.abego.treelayout.core:1.0.3
          |    |    |    +--- org.glassfish:javax.json:1.0.4
          |    |    |    \--- com.ibm.icu:icu4j:61.1
          |    |    +--- com.squareup.okio:okio:2.6.0 (*)
          |    |    +--- com.google.guava:guava:29.0-jre
          |    |    |    +--- com.google.guava:failureaccess:1.0.1
          |    |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
          |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
          |    |    |    +--- org.checkerframework:checker-qual:2.11.1
          |    |    |    +--- com.google.errorprone:error_prone_annotations:2.3.4
          |    |    |    \--- com.google.j2objc:j2objc-annotations:1.3
          |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72
          |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72
          |    |              \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- com.microsoft.thrifty:thrifty-compiler-plugins:2.1.1
          |    |    +--- com.squareup:javapoet:1.11.1
          |    |    +--- com.squareup:kotlinpoet:1.5.0
          |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61 -> 1.3.72 (*)
          |    |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.72
          |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- com.squareup.okio:okio:2.6.0 (*)
          |    +--- com.squareup:javapoet:1.11.1
          |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
          +--- com.microsoft.thrifty:thrifty-kotlin-codegen:2.1.1
          |    +--- com.squareup:kotlinpoet:1.5.0 (*)
          |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 (*)
          |    +--- com.microsoft.thrifty:thrifty-runtime-ktx:2.1.1
          |    |    +--- com.microsoft.thrifty:thrifty-runtime:2.1.1 (*)
          |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
          |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6
          |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.71 -> 1.3.72 (*)
          |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.71 -> 1.3.72
          |    +--- com.microsoft.thrifty:thrifty-schema:2.1.1 (*)
          |    +--- com.microsoft.thrifty:thrifty-compiler-plugins:2.1.1 (*)
          |    +--- com.squareup.okio:okio:2.6.0 (*)
          |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
          +--- com.microsoft.thrifty:thrifty-schema:2.1.1 (*)
          +--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72
          |    +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 (*)
          |    |    +--- org.jetbrains.kotlin:kotlin-daemon-embeddable:1.3.72
          |    |    \--- org.jetbrains.intellij.deps:trove4j:1.0.20181211
          |    +--- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72 (*)
          |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-android-extensions:1.3.72
          |    |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-compiler-runner:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-build-common:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-daemon-client:1.3.72
          |    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 (*)
          |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.6 (*)
          |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.6 (*)
          |    +--- org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.72
          |    |    |    +--- org.jetbrains.kotlin:kotlin-scripting-common:1.3.72
          |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.6 (*)
          |    |    |    +--- org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.72
          |    |    |    |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.72
          |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    |    |    \--- org.jetbrains.kotlin:kotlin-scripting-common:1.3.72 (*)
          |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.6 (*)
          |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    \--- org.jetbrains.kotlin:kotlin-native-utils:1.3.72
          |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |         \--- org.jetbrains.kotlin:kotlin-util-io:1.3.72
          |    |              \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.3.72
          |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-native-utils:1.3.72 (*)
          |    +--- org.jetbrains.kotlin:kotlin-util-klib:1.3.72
          |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
          |    |    \--- org.jetbrains.kotlin:kotlin-util-io:1.3.72 (*)
          |    +--- com.google.code.gson:gson:2.8.5
          |    \--- de.undercouch:gradle-download-task:4.0.2
          \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)

(*) - dependencies omitted (listed previously)
```
</details>

I unfortunately don't see any references to ANTLR 4.5.3 in there, though.

**Pull request merged**
