### PR TITLE
Add the Struct Interface and make generated Thrift structs implement it

### PR DESCRIPTION
**Pull request by seanabraham**
Per https://github.com/Microsoft/thrifty/issues/39 this adds the `Struct` interface which has a `write` method and makes all generated Thrift structs implement it. This will add one method per generated struct but with the advantage that a generic `Struct` can be written out to a protocol.

For example, this is now possible:

```java
Buffer buffer = new Buffer();
Transport transport = new BufferTransport(buffer);
Protocol protocol = new BinaryProtocol(transport):

Struct fooStruct = Foo.Builder().build();
Struct barStruct = Bar.Builder().build();

fooStruct.write(protocol);
barStruct.write(protocol);
```

Paired with @felipecsl

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Hi, thanks for the speedy PR and CLA!

It looks like this failed checkstyle; please run `./gradlew check` and fix whatever it is complaining about, usually it's very minor.

This is quite useful as-is; now that I see this, however, I'm wondering if it might be better to have `Struct` as a common base class rather than an interface.  It would then be trivial to say:
```java
protected abstract Adapter<T, B> adapter();
public void serialize(Protocol protocol) {
  adapter().write(protocol, (T) this);
}
```

Not a huge difference yet, but it would lay the groundwork for adding common functions to generated classes without codegen.

What do you think?

**Comment by felipecsl** [comment]
+1 for that suggestioN!

**Comment by seanabraham** [comment]
Good idea, I'll fix the checkstyle real quick (missing period in javadoc) and then modify the change to extend from `Struct` instead.

**Comment by seanabraham** [comment]
So, one issue with extending from a `Struct` abstract class as opposed to implementing a `Struct` interface is the existing behavior in the `buildStruct` method. It looks like if the `StructType` is `StructElement.Type.EXCEPTION` the generated class is meant to be a subclass of `Exception`:

```
    if (type.isException()) {
      structBuilder.superclass(Exception.class);
    }
```

**Comment by benjamin-bader** [comment]
Of course - how could I forget!  That certainly complicates things.

It's really a shame that, even with the new Java 8 features coming in Android N, default methods on interfaces will not be supported below API 24; that would give us the best of all worlds.  I suppose we can proceed with an interface.

Thanks for your contribution!

**Pull request merged**
