### PR TITLE
fix for catch-all * namespace #325

### PR DESCRIPTION
**Pull request by timvlaer**
See #325

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Thanks for contributing!

Looks like our CI is broken - I'll fix it.  Although your change is low-risk, I'd ask that you rebase once CI is working again so we can get a proper build.

**Comment by benjamin-bader** [comment]
OK, CI is fixed - please do rebase off of master, so we can get a green build.  Thanks again!

**Comment by timvlaer** [comment]
Rebased on master and test case added

**Comment by benjamin-bader** [comment]
Awesome, looks great - thanks for your contribution!

**Pull request merged**
