### PR TITLE
Fix reading bool value using compact protocol

### PR DESCRIPTION
**Pull request by reisub**
We came across an issue in deserializing a bool value using compact protocol - the value always comes out false.

This PR modifies the test so that it catches this bug and fixes it.

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Excellent catch - thanks for the fix!  Would you mind including the thrift change you made to Xtruct as well, so we don't lose it if/when we ever regenerate it?

**Comment by reisub** [comment]
@benjamin-bader done in https://github.com/Microsoft/thrifty/pull/153/commits/8840ab3eef372bddb5fb22fcac0170f2df11de0c, though I'm not sure which exact file you wanted changed since there are none in the `thrift-runtime` module.

**Comment by benjamin-bader** [comment]
Perfect.  There's no one file, sadly - we seem to have overlooked automating generating this file, probably because it is done so infrequently.  I think this would only be the second version.

I'm comfortable calling the integration-test file the "source of truth" here.

**Comment by benjamin-bader** [comment]
Merged - thanks again!

**Pull request merged**
