### PR TITLE
Add initial spike of big-enum support

### PR DESCRIPTION
**Pull request by benjamin-bader**
This is a rough draft of support for issue #406; at minimum, this also requires work to add a compiler flag to enable this mode (currently hardcoded).

@shashachu If you can, please give this a whirl and let me know if it works for you.  It's working for me, but I have a feeling that the integration tests we have are not sufficient to catch the kinds of bugs that would surface for something as big as your app.

### CODE REVIEW

**Comment by shashachu** [comment]
Wow, fast service! We'll give it a try internally and report back.

**Comment by benjamin-bader** [comment]
Hi @shashachu - how did it go?  (or is it still ongoing?)

**Comment by shashachu** [comment]
Hi, sorry I haven't had a chance to test it out yet.

**Comment by shashachu** [comment]
Hey @benjamin-bader - so I've run into a couple issues using your snapshot on our codebase.

First, it doesn't seem to generate the proper imports for the `.value` extension function if the class it's referencing is in a different package than the current class. e.g.

```
package com.bar.foo

enum MyBigEnum {
    ...
}

val MyBigEnum.value: Int
    get() = ...
```

```
package com.foo.bar

// there will be a missing import for com.bar.foo.value

data class MyClass {
    ...
    override fun write(protocol: Protocol, struct: InterestReasonDetails): Unit {
      protocol.writeStructBegin("MyClass")
      if (struct.myBigEnum != null) {
        protocol.writeFieldBegin("myBigEnum", 1, TType.I32)
        protocol.writeI32(struct.myBigEnum.value)
        protocol.writeFieldEnd()
      }
     ...
    }
```

If I manually add the imports in, the build eventually fails with several `Duplicate JVM class name` errors, which appears to be this bug: https://youtrack.jetbrains.com/issue/KT-21186

I'm going to try implementing it as a regular member function instead of an extension function.

**Comment by benjamin-bader** [comment]
Interesting!  Thanks for trying this out and reporting back.  I'm definitely curious about the how the member-function experiment works out.

**Comment by shashachu** [comment]
@benjamin-bader Happy New Year! Finally got back to this work after the holidays, and it does appear to work when converting `value` into a regular function rather than an extension function. I honestly am unsure if we're simply kicking the can down the road, but everything builds for us.

I hacked it in essentially by inserting this code into `generateEnumClass`:

```
val value = FunSpec.builder("value")
  .returns(Int::class).apply {
      beginControlFlow("return when (this)")
      for (member in enumType.members) {
          val name = nameAllocator[member]
          addStatement("%L -> %L", name, member.value)
      }
      endControlFlow()
  }
  .build()

  ...

return typeBuilder
  .addType(companion)
  .addFunction(value)
  .build()
```

**Comment by shashachu** [comment]
@benjamin-bader checking in again to see your thoughts about whether something like this could be merged into master. If not, we can certainly fork but we'd like to know sooner rather than later. Thanks!

**Comment by benjamin-bader** [comment]
@shashachu thanks for your patience - life got pretty hectic this past month and I haven't checked notifications in a long time!

At this point, I'm happy to take a PR that helps you so long as it's behind a compiler flag.  Agreed  that this is probably just kicking the can down the road, but that's often a valid choice to make (and isn't my business in the first place).

**Comment by benjamin-bader** [comment]
Implemented in #421

**Pull request closed without merging**
